# Generated by Django 5.1.8 on 2026-09-08 04:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('BUDGET_NEAR', 'Budget near limit'), ('BUDGET_EXCEEDED', 'Budget exceeded'), ('RECURRING_DUE', 'Recurring expense due'), ('MONTHLY_SUMMARY', 'Monthly summary'), ('GOAL_REMINDER', 'Savings goal reminder')], max_length=32)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(blank=True, default='', max_length=160)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='families.family')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['family', 'read_at'], name='notificatio_family__72856e_idx'), models.Index(fields=['family', 'dedupe_key'], name='notificatio_family__91ae08_idx')],
            },
        ),
    ]
