# Generated by Django 5.1.8 on 2026-09-08 03:56

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year_month', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='catalogs.category')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_budgets', to='families.family')),
            ],
            options={
                'ordering': ['category__name'],
                'indexes': [models.Index(fields=['family', 'year_month'], name='planning_ca_family__ae3e85_idx')],
                'unique_together': {('family', 'year_month', 'category')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year_month', models.DateField(help_text='First day of the month.')),
                ('overall_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_budgets', to='families.family')),
            ],
            options={
                'ordering': ['-year_month'],
                'indexes': [models.Index(fields=['family', 'year_month'], name='planning_mo_family__7b91b3_idx')],
                'unique_together': {('family', 'year_month')},
            },
        ),
        migrations.CreateModel(
            name='SubcategoryBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year_month', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_budgets', to='families.family')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='catalogs.subcategory')),
            ],
            options={
                'unique_together': {('family', 'year_month', 'subcategory')},
            },
        ),
    ]
