# Generated by Django 5.1.8 on 2026-09-08 05:29

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
        ('families', '0002_familymember_role_familyinvitation'),
        ('planning', '0002_financialgoal_recurringexpense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalContribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_withdrawal', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('occurred_on', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goal_contributions', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_contributions', to='families.family')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='planning.financialgoal')),
            ],
            options={
                'ordering': ['-occurred_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('due_date', models.DateField()),
                ('frequency', models.CharField(choices=[('ONCE', 'One time'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=16)),
                ('reminder_days', models.PositiveSmallIntegerField(default=3)),
                ('auto_post', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('DUE_TODAY', 'Due today'), ('OVERDUE', 'Overdue'), ('PAID', 'Paid'), ('SKIPPED', 'Skipped')], default='UPCOMING', max_length=16)),
                ('last_paid_on', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='catalogs.category')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='families.family')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='families.familymember')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='catalogs.paymentmethod')),
            ],
            options={
                'ordering': ['due_date', 'title'],
                'indexes': [models.Index(fields=['family', 'is_active', 'due_date'], name='planning_bi_family__d2af87_idx')],
            },
        ),
    ]
