# Generated by Django 5.1.8 on 2026-09-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_goalcontribution_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='frequency',
            field=models.CharField(default='MONTHLY', max_length=16),
        ),
        migrations.AlterField(
            model_name='financialgoal',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=16),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='frequency',
            field=models.CharField(max_length=16),
        ),
    ]
