# Generated by Django 5.1.8 on 2026-09-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0002_familymember_role_familyinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='relationship',
            field=models.CharField(default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='role',
            field=models.CharField(default='EDITOR', max_length=16),
        ),
    ]
