# Generated by Django 5.1.8

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterValue",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("group", models.CharField(max_length=40)),
                ("code", models.CharField(max_length=40)),
                ("label", models.CharField(max_length=80)),
                ("icon", models.CharField(blank=True, default="", max_length=64)),
                ("color", models.CharField(blank=True, default="", max_length=16)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("extra", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["group", "sort_order", "label"],
            },
        ),
        migrations.AddConstraint(
            model_name="mastervalue",
            constraint=models.UniqueConstraint(fields=("group", "code"), name="uniq_master_group_code"),
        ),
        migrations.AddIndex(
            model_name="mastervalue",
            index=models.Index(fields=["group", "is_active", "sort_order"], name="catalogs_master_group_idx"),
        ),
    ]
