# Generated by Django 5.1.8 on 2026-09-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_mastervalue'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mastervalue',
            new_name='catalogs_ma_group_ce9756_idx',
            old_name='catalogs_master_group_idx',
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(max_length=16),
        ),
    ]
