# Generated by Django 5.1.8 on 2026-09-08 03:56

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        ('families', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('EXPENSE', 'Expense'), ('INCOME', 'Income'), ('SAVING', 'Saving')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('occurred_on', models.DateField()),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('client_id', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('category_name_snapshot', models.CharField(max_length=80)),
                ('subcategory_name_snapshot', models.CharField(blank=True, default='', max_length=80)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='catalogs.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='families.family')),
                ('member', models.ForeignKey(help_text='Paid by (expense/saving) or received by (income).', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='families.familymember')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='catalogs.paymentmethod')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='catalogs.subcategory')),
            ],
            options={
                'ordering': ['-occurred_on', '-created_at'],
                'indexes': [models.Index(fields=['family', 'occurred_on'], name='ledger_fina_family__5eb306_idx'), models.Index(fields=['family', 'type', 'occurred_on'], name='ledger_fina_family__46496d_idx'), models.Index(fields=['family', 'category'], name='ledger_fina_family__5019b1_idx'), models.Index(fields=['family', 'member'], name='ledger_fina_family__810b2d_idx'), models.Index(fields=['family', 'payment_method'], name='ledger_fina_family__da5b8f_idx'), models.Index(fields=['family', 'is_deleted', 'occurred_on'], name='ledger_fina_family__b9c6da_idx'), models.Index(fields=['created_at'], name='ledger_fina_created_2c71d2_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='txn_amount_gt_zero'), models.UniqueConstraint(condition=models.Q(('client_id__isnull', False)), fields=('family', 'client_id'), name='uniq_family_client_id')],
            },
        ),
    ]
