# Generated by Django 5.1.8 on 2026-09-08 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
        ('planning', '0002_financialgoal_recurringexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='recurring_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_transactions', to='planning.recurringexpense'),
        ),
    ]
