# Generated by Django 5.1.8 on 2026-09-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_financialtransaction_recurring_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
