# Generated by Django 5.1.8 on 2026-09-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_financialtransaction_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialtransaction',
            name='type',
            field=models.CharField(max_length=16),
        ),
    ]
